[package]
name = "bae-server"
version = "0.0.0-dev"
authors = ["dima"]
edition = "2021"

[[bin]]
name = "bae-server"
path = "src/main.rs"

[dependencies]
bae-core = { path = "../bae-core" }
clap = { version = "4.5", features = ["derive", "env"] }
tokio = { version = "1.0", features = ["full"] }
axum = "0.7"
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }

[lints.clippy]
too_many_arguments = "allow"
